version: '3.1'
services:
  app:
    container_name: gvcmanagement_app
    image: gvcmanagement
    build: ./
    volumes:
    - /tmp
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    container_name: gvc_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userservice